name: Feature request
description: Propón una mejora
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: textarea
    id: goal
    attributes:
      label: Objetivo
      description: Qué quieres lograr
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Propuesta
      description: Cómo lo implementarías (API, outputs, tests)